# An example of ClusterConfig object with custom VPC IPv4 CIDR,
# and auto-allocated IPv6 CIDRs for all subnets; also without
# any nodegroups:
# https://eksctl.io/usage/eks-managed-nodes/
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-with-custom-vpc
  region: ap-northeast-1
  version: "1.28"

vpc:
  cidr: 10.10.0.0/16
  hostnameType: resource-name
  # disable public access to endpoint and only allow private access
  clusterEndpoints:
    publicAccess: true

managedNodeGroups:
  - name: ng-apps
    instanceType: c6g.medium
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20