apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-with-custom-vpc-pri-ng
  region: ap-northeast-1
  version: "1.28"

vpc:
  cidr: 10.10.0.0/16
  hostnameType: resource-name
  clusterEndpoints:
    publicAccess: true

managedNodeGroups:
  - name: ng-apps
    instanceType: c6i.large
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20
    privateNetworking: true